# Site settings
title: CW
email: chelseaworrel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Chelsea Worrel: I write code. 
  <ul>
  <li>Ruby Fundamentals, Object-Oriented Programming, and Test-Driven Development</li>
  <li>Ruby Web Applications with Sinatra and Rails</li>
  <li>Professional Web Applications, Security, and Agile Methodologies</li>
  <li>Performance, APIs, Services, and Client-Side JavaScript</li>

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chelseaworrel.github.io" # the base hostname & protocol for your site
twitter_username: chelsea_worrel
github_username:  chelseaworrel

# Build settings
markdown: kramdown
